version: 2
jobs:
  build:
    docker:
      - image: ishiko/gcc-ishiko-cpp:0.1.0
    steps:
      - checkout:
          path: /DiplodocusDB/Core
      - run:
          name: Build
          command: cd /DiplodocusDB/Core/Makefiles/GNUmakefile && make
